pipeline {
    agent any
    stages {
        stage('clean') {
            steps {
                echo "Maven Clean Started"
                bat 'mvn -B clean verify'
                echo "Maven Clean Completed"
            }
        }
//stage ('test'){
//steps{
  //  echo "Maven Test Started"
  //  bat 'mvn -B test verify'
  //  echo "Maven test Completed"
  //  }
 // }
        stage ('build'){
        steps{
            echo "Maven package Started"
                bat 'mvn -B package verify'
           echo "Maven package Completed"
            
            }

 }
        // stage ('deploy'){
      //  steps{
         //   echo "Maven deploy Started"
          //      bat 'java -jar -Dserver.port=8888 target\\student-services-security-0.0.1-SNAPSHOT.jar'
         //  echo "Maven deploy Completed"
            
          //  }

 //}
        
          stage('SonarQube analysis') {
    withSonarQubeEnv('My SonarQube Server') {
      // requires SonarQube Scanner for Maven 3.2+
      bat 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
    }
  }


        
}
}

